name: pyfitenv
channels:
  - conda-forge

dependencies:
  - python==3.8
  - cmake
  - arrow-cpp
  - pybind11
  - defusedxml
  - setuptools
  - mkdocs

  # For notebook tests
  - nodejs
  - jupyterlab
  - pandas
  - openjdk
  - pyarrow
  - pyspark
