name: pyfitenv-dev
channels:
  - conda-forge
dependencies:
  - python==3.8
  - cmake
  - boost
  - arrow-cpp
  - jupyterlab
  - defusedxml
  - mkdocs
  - openjdk
  - pandas
  - pip
  - pyarrow
  - pybind11
  - pyspark
  - pip:
      - .
