name: pyfitenv
channels:
  - conda-forge

dependencies:
  - python==3.8
  - cmake
  - boost
  - arrow-cpp
  - pybind11
  - defusedxml
  - pandas
  - pyarrow

  # For pip install
  - setuptools
  - pip

  # For documentation
  - mkdocs

  # For notebooks
  - nodejs
  - jupyterlab
