###########################################################################################################
# Note: The USER/CLIENT is expected to fine tune parameters: MESG_TAGS, TIMESTAMP_TAGS, TAG_FIELD_EXCLUDES
# and TAG_FIELD_MAP appropriately to match your TCX data and map it to parquet format as preferred (thus 
# making it comparable to how your FIT file data is serialized). When parsing TCX files, tcxtransformer.py 
# will log to stdout any values it discovers w/o valid endpoints specified in TAG_FIELD_MAP (to quiet this 
# behavior, each missing endpoint must be added to TAG_FIELD_EXCLUDES). This allows you to append missing 
# endpoints and rerun the tcxtranformer serialization.
#
# The bottom of this file contains effectively the full set of possible endpoints defined in Garmin's 
# TrainingCenterDatabasev2.xsd schema file for reference (though additional TCX endpoints may still occur 
# due to adhoc schema extensions and recursive, complexType "loops" included in the Garmin schema.


# Tags defined comparable (by convention) to FIT mesgs. These should 
# correspond to choice of mesg_name fields in TAG_FIELD_MAP below.
MESG_TAGS = {'Author', 'Activity', 'Creator', 'Lap', 'Trackpoint'}

# Tags endpoints (when encountered) that should overwrite current timestamp column value
TIMESTAMP_TAGS = {'TrainingCenterDatabase-Activities-Activity-Id',
                  'TrainingCenterDatabase-Activities-Activity-Lap-StartTime',
                  'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Time'}

# Tag endpoints (likely w/a valid field_value) to exclude/skip/ignore 
TAG_FIELD_EXCLUDES = {'TrainingCenterDatabase-schemaLocation',
                      'TrainingCenterDatabase-noNamespaceSchemaLocation'}

# Tag endpoint mappings : [mesg_name, field_name, units]
TAG_FIELD_MAP = {
    'TrainingCenterDatabase-Author-type': ['Author', 'type', None],

    'TrainingCenterDatabase-Activities-Activity-Sport': ['Activity', 'sport', None],
    'TrainingCenterDatabase-Activities-Activity-Id': ['Activity', 'id', None],

    'TrainingCenterDatabase-Activities-Activity-Creator-type': ['Creator', 'type', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Name': ['Creator', 'name', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-ProductID': ['Creator', 'product_id', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-UnitId': ['Creator', 'unit_id', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Version-BuildMajor': ['Creator', 'build_major', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Version-BuildMinor': ['Creator', 'build_minor', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Version-VersionMajor': ['Creator', 'version_major', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Version-VersionMinor': ['Creator', 'version_minor', None],

    'TrainingCenterDatabase-Activities-Activity-Lap-StartTime': ['Lap', 'start_time', 's'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Calories': ['Lap', 'calories', 'kcal'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Intensity': ['Lap', 'intensity', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-TriggerMethod': ['Lap', 'trigger_method', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-MaximumSpeed': ['Lap', 'maximum_speed', 'm/s'],
    'TrainingCenterDatabase-Activities-Activity-Lap-DistanceMeters': ['Lap', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-TotalTimeSeconds': ['Lap', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-Activity-Lap-AverageHeartRateBpm-Value': ['Lap', 'average_heart_rate', 'bpm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-MaximumHeartRateBpm-Value': ['Lap', 'maximum_heart_rate', 'bpm'],

    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Cadence': ['Trackpoint', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-DistanceMeters': ['Trackpoint', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Extensions-TPX-Speed': ['Trackpoint', 'Speed', 'm/s'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Extensions-TPX-Watts': ['Trackpoint', 'power', 'watts'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-HeartRateBpm-Value': ['Trackpoint', 'heart_rate', 'bmp'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Time': ['Trackpoint', 'timestamp', 's'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Position-LatitudeDegrees' : ['Trackpoint', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Position-LongitudeDegrees' : ['Trackpoint', 'longitude', 'degrees']
}


######################################################################################################
# The following is the full endpoint set (not including allowable recursive schema definitions,
# which can result in infinite length endpoints) autogenerated by genmapping.py from the Garmin
# TrainingCenterDatabasev2.xsd schema file (both are available in this repo). It is meant as a
# base for USER/CLIENT reference only, TRAINING_CENTER_DATABASE_XSD_DEFAULT_ENDPOINT_MAPPINGS 
# is NEVER accessed directly by tcxtransformer.py on TCX data parasing. The USER/CLIENT is expected 
# to add any of the endpoints (or others not explict in TrainingCenterDatabasev2.xsd) to TAG_FIELD_MAP
# above and to verify the choice of [mesg_name, field_name, units] to match their preferred mapping.

TRAINING_CENTER_DATABASE_XSD_DEFAULT_ENDPOINT_MAPPINGS = {
    'TrainingCenterDatabase-Folders-History-Running-Folder-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Running-Folder-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Running-Folder-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Running-Folder-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Running-Folder-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Running-Folder-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Running-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Running-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Running-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Running-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Running-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Running-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Biking-Folder-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Biking-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Biking-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Biking-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Biking-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Biking-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Biking-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Other-Folder-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Other-ActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-Other-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Other-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-Other-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-Other-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-Other-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-MultisportActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Folder-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-MultisportActivityRef-Id' : ['History', 'id', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Week-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Week-StartDay' : ['History', 'start_day', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Notes' : ['History', 'notes', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Extensions' : ['History', 'extensions', None],
    'TrainingCenterDatabase-Folders-History-MultiSport-Name' : ['History', 'name', None],
    'TrainingCenterDatabase-Folders-History-Extensions' : ['History', 'extensions', None],

    'TrainingCenterDatabase-Folders-Workouts-Running-Folder-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Running-Folder-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Running-Folder-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Running-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Running-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Running-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-Folder-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-Folder-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-Folder-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Biking-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-Folder-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-Folder-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-Folder-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-WorkoutNameRef-Id' : ['Workouts', 'id', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-Extensions' : ['Workouts', 'extensions', None],
    'TrainingCenterDatabase-Folders-Workouts-Other-Name' : ['Workouts', 'name', None],
    'TrainingCenterDatabase-Folders-Workouts-Extensions' : ['Workouts', 'extensions', None],

    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Folder-CourseNameRef-Id' : ['Courses', 'id', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Folder-Notes' : ['Courses', 'notes', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Folder-Extensions' : ['Courses', 'extensions', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Folder-Name' : ['Courses', 'name', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-CourseNameRef-Id' : ['Courses', 'id', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Notes' : ['Courses', 'notes', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Extensions' : ['Courses', 'extensions', None],
    'TrainingCenterDatabase-Folders-Courses-CourseFolder-Name' : ['Courses', 'name', None],
    'TrainingCenterDatabase-Folders-Courses-Extensions' : ['Courses', 'extensions', None],

    'TrainingCenterDatabase-Activities-Activity-Id' : ['Activity', 'id', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-TotalTimeSeconds' : ['Activity', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-Activity-Lap-DistanceMeters' : ['Activity', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-MaximumSpeed' : ['Activity', 'maximum_speed', 'm/s'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Calories' : ['Activity', 'calories', 'kcal'],
    'TrainingCenterDatabase-Activities-Activity-Lap-AverageHeartRateBpm-Value' : ['Activity', 'value', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-MaximumHeartRateBpm-Value' : ['Activity', 'value', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Intensity' : ['Activity', 'intensity', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Cadence' : ['Activity', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-TriggerMethod' : ['Activity', 'trigger_method', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Time' : ['Activity', 'timestamp', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Position-LatitudeDegrees' : ['Activity', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Position-LongitudeDegrees' : ['Activity', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-AltitudeMeters' : ['Activity', 'altitude', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-DistanceMeters' : ['Activity', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-HeartRateBpm-Value' : ['Activity', 'value', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Cadence' : ['Activity', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-SensorState' : ['Activity', 'sensor_state', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Track-Trackpoint-Extensions' : ['Activity', 'extensions', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Notes' : ['Activity', 'notes', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-Extensions' : ['Activity', 'extensions', None],
    'TrainingCenterDatabase-Activities-Activity-Lap-StartTime' : ['Activity', 'start_time', None],
    'TrainingCenterDatabase-Activities-Activity-Notes' : ['Activity', 'notes', None],
    'TrainingCenterDatabase-Activities-Activity-Training-QuickWorkoutResults-TotalTimeSeconds' : ['Activity', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-Activity-Training-QuickWorkoutResults-DistanceMeters' : ['Activity', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-Activity-Training-Plan-Name' : ['Activity', 'name', None],
    'TrainingCenterDatabase-Activities-Activity-Training-Plan-Extensions' : ['Activity', 'extensions', None],
    'TrainingCenterDatabase-Activities-Activity-Training-Plan-Type' : ['Activity', 'type', None],
    'TrainingCenterDatabase-Activities-Activity-Training-Plan-IntervalWorkout' : ['Activity', 'interval_workout', None],
    'TrainingCenterDatabase-Activities-Activity-Training-VirtualPartner' : ['Activity', 'virtual_partner', None],
    'TrainingCenterDatabase-Activities-Activity-Creator-Name' : ['Activity', 'name', None],
    'TrainingCenterDatabase-Activities-Activity-Extensions' : ['Activity', 'extensions', None],
    'TrainingCenterDatabase-Activities-Activity-Sport' : ['Activity', 'sport', None],

    'TrainingCenterDatabase-Activities-MultiSportSession-Id' : ['MultiSportSession', 'id', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Id' : ['MultiSportSession', 'id', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-TotalTimeSeconds' : ['MultiSportSession', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-MaximumSpeed' : ['MultiSportSession', 'maximum_speed', 'm/s'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Calories' : ['MultiSportSession', 'calories', 'kcal'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-AverageHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-MaximumHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Intensity' : ['MultiSportSession', 'intensity', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-TriggerMethod' : ['MultiSportSession', 'trigger_method', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-Time' : ['MultiSportSession', 'timestamp', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-Position-LatitudeDegrees' : ['MultiSportSession', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-Position-LongitudeDegrees' : ['MultiSportSession', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-AltitudeMeters' : ['MultiSportSession', 'altitude', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-HeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-SensorState' : ['MultiSportSession', 'sensor_state', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Track-Trackpoint-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Notes' : ['MultiSportSession', 'notes', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Lap-StartTime' : ['MultiSportSession', 'start_time', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Notes' : ['MultiSportSession', 'notes', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-QuickWorkoutResults-TotalTimeSeconds' : ['MultiSportSession', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-QuickWorkoutResults-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-Plan-Name' : ['MultiSportSession', 'name', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-Plan-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-Plan-Type' : ['MultiSportSession', 'type', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-Plan-IntervalWorkout' : ['MultiSportSession', 'interval_workout', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Training-VirtualPartner' : ['MultiSportSession', 'virtual_partner', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Creator-Name' : ['MultiSportSession', 'name', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-FirstSport-Activity-Sport' : ['MultiSportSession', 'sport', None],

    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-TotalTimeSeconds' : ['MultiSportSession', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-MaximumSpeed' : ['MultiSportSession', 'maximum_speed', 'm/s'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Calories' : ['MultiSportSession', 'calories', 'kcal'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-AverageHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-MaximumHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Intensity' : ['MultiSportSession', 'intensity', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-TriggerMethod' : ['MultiSportSession', 'trigger_method', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-Time' : ['MultiSportSession', 'timestamp', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-Position-LatitudeDegrees' : ['MultiSportSession', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-Position-LongitudeDegrees' : ['MultiSportSession', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-AltitudeMeters' : ['MultiSportSession', 'altitude', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-HeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-SensorState' : ['MultiSportSession', 'sensor_state', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Track-Trackpoint-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Notes' : ['MultiSportSession', 'notes', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Transition-StartTime' : ['MultiSportSession', 'start_time', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Id' : ['MultiSportSession', 'id', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-TotalTimeSeconds' : ['MultiSportSession', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-MaximumSpeed' : ['MultiSportSession', 'maximum_speed', 'm/s'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Calories' : ['MultiSportSession', 'calories', 'kcal'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-AverageHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-MaximumHeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Intensity' : ['MultiSportSession', 'intensity', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-TriggerMethod' : ['MultiSportSession', 'trigger_method', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-Time' : ['MultiSportSession', 'timestamp', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-Position-LatitudeDegrees' : ['MultiSportSession', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-Position-LongitudeDegrees' : ['MultiSportSession', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-AltitudeMeters' : ['MultiSportSession', 'altitude', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-HeartRateBpm-Value' : ['MultiSportSession', 'value', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-Cadence' : ['MultiSportSession', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-SensorState' : ['MultiSportSession', 'sensor_state', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Track-Trackpoint-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Notes' : ['MultiSportSession', 'notes', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Lap-StartTime' : ['MultiSportSession', 'start_time', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Notes' : ['MultiSportSession', 'notes', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-QuickWorkoutResults-TotalTimeSeconds' : ['MultiSportSession', 'total_time', 's'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-QuickWorkoutResults-DistanceMeters' : ['MultiSportSession', 'distance', 'm'],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-Plan-Name' : ['MultiSportSession', 'name', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-Plan-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-Plan-Type' : ['MultiSportSession', 'type', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-Plan-IntervalWorkout' : ['MultiSportSession', 'interval_workout', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Training-VirtualPartner' : ['MultiSportSession', 'virtual_partner', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Creator-Name' : ['MultiSportSession', 'name', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Extensions' : ['MultiSportSession', 'extensions', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-NextSport-Activity-Sport' : ['MultiSportSession', 'sport', None],
    'TrainingCenterDatabase-Activities-MultiSportSession-Notes' : ['MultiSportSession', 'notes', None],

    'TrainingCenterDatabase-Workouts-Workout-Name' : ['Workout', 'name', None],
    'TrainingCenterDatabase-Workouts-Workout-Step-StepId' : ['Workout', 'step_id', None],
    'TrainingCenterDatabase-Workouts-Workout-ScheduledOn' : ['Workout', 'scheduled_on', None],
    'TrainingCenterDatabase-Workouts-Workout-Notes' : ['Workout', 'notes', None],
    'TrainingCenterDatabase-Workouts-Workout-Creator-Name' : ['Workout', 'name', None],
    'TrainingCenterDatabase-Workouts-Workout-Extensions' : ['Workout', 'extensions', None],
    'TrainingCenterDatabase-Workouts-Workout-Sport' : ['Workout', 'sport', None],

    'TrainingCenterDatabase-Courses-Course-Name' : ['Course', 'name', None],
    'TrainingCenterDatabase-Courses-Course-Lap-TotalTimeSeconds' : ['Course', 'total_time', 's'],
    'TrainingCenterDatabase-Courses-Course-Lap-DistanceMeters' : ['Course', 'distance', 'm'],
    'TrainingCenterDatabase-Courses-Course-Lap-BeginPosition-LatitudeDegrees' : ['Course', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Lap-BeginPosition-LongitudeDegrees' : ['Course', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Lap-BeginAltitudeMeters' : ['Course', 'begin_altitude', 'm'],
    'TrainingCenterDatabase-Courses-Course-Lap-EndPosition-LatitudeDegrees' : ['Course', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Lap-EndPosition-LongitudeDegrees' : ['Course', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Lap-EndAltitudeMeters' : ['Course', 'end_altitude', 'm'],
    'TrainingCenterDatabase-Courses-Course-Lap-AverageHeartRateBpm-Value' : ['Course', 'value', None],
    'TrainingCenterDatabase-Courses-Course-Lap-MaximumHeartRateBpm-Value' : ['Course', 'value', None],
    'TrainingCenterDatabase-Courses-Course-Lap-Intensity' : ['Course', 'intensity', None],
    'TrainingCenterDatabase-Courses-Course-Lap-Cadence' : ['Course', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Courses-Course-Lap-Extensions' : ['Course', 'extensions', None],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-Time' : ['Course', 'timestamp', None],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-Position-LatitudeDegrees' : ['Course', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-Position-LongitudeDegrees' : ['Course', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-AltitudeMeters' : ['Course', 'altitude', 'm'],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-DistanceMeters' : ['Course', 'distance', 'm'],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-HeartRateBpm-Value' : ['Course', 'value', None],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-Cadence' : ['Course', 'cadence', 'rpm'],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-SensorState' : ['Course', 'sensor_state', None],
    'TrainingCenterDatabase-Courses-Course-Track-Trackpoint-Extensions' : ['Course', 'extensions', None],
    'TrainingCenterDatabase-Courses-Course-Notes' : ['Course', 'notes', None],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Name' : ['Course', 'name', None],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Time' : ['Course', 'timestamp', None],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Position-LatitudeDegrees' : ['Course', 'latitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Position-LongitudeDegrees' : ['Course', 'longitude', 'degrees'],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-AltitudeMeters' : ['Course', 'altitude', 'm'],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-PointType' : ['Course', 'point_type', None],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Notes' : ['Course', 'notes', None],
    'TrainingCenterDatabase-Courses-Course-CoursePoint-Extensions' : ['Course', 'extensions', None],
    'TrainingCenterDatabase-Courses-Course-Creator-Name' : ['Course', 'name', None],
    'TrainingCenterDatabase-Courses-Course-Extensions' : ['Course', 'extensions', None],

    'TrainingCenterDatabase-Author-Name' : ['Author', 'name', None],
    'TrainingCenterDatabase-Extensions' : ['TrainingCenterDatabase', 'extensions', None]
}
