{% set pyfit_version = "1.0" %}
{% set fitsdk_version = "FitCppSDK_21.47.00" %}


package:
  name: pyfitparquet
  version: {{ pyfit_version }}

source:
  url: https://github.com/databike-io/pyfitparquet/releases/download/{{ pyfit_version }}/pyfitparquet-{{ pyfit_version }}.tar.gz
  sha256: d3cb5a589889b498a14b5d98d0ff341be3a6de9dd7308495a6d28ff735dd5878

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - boost-cpp {{ boostcpp }}
    - arrow-cpp
    - pybind11
  run:
    - python {{ python }}
    - boost-cpp {{ boostcpp }}
    - boost
    - pyyaml
    - defusedxml
    - pandas
    - pyarrow

test:
  source_files:
    - test

about:
  home: https://github.com/databike-io/pyfitparquet
  license: Apache-2.0
  license_family: APACHE
  license_file: 
    - LICENSE
    - pyfitparquet/{{ fitsdk_version }}/GARMIN_FIT_SDK_LICENSE
  summary: 'ETL support of Garmin FIT/TCX files to Apache Parquet'
  description: |
    The pyfitparquet package provides support for Garmin [FIT](https://developer.garmin.com/fit/overview/) and 
    [TCX](https://en.wikipedia.org/wiki/Training_Center_XML) file ETL into [Apache Parquet](https://parquet.apache.org/) 
    columnar format. It leverages the fast Garmin SDK CPP decoding interface for FIT files and pure Python for TCX files.
  doc_url: https://databike-io.github.io/pyfitparquet/
  dev_url: https://github.com/databike-io/pyfitparquet

extra:
  recipe-maintainers:
    - ajdonich
